export const collectionNames = {
    users : 'user',
    offers : 'offers',
    categories : 'categories',
    products: 'products',
    hoacaykieng : 'hoacaykieng',
    nhavuons : 'nhavuons',
    rongrieu : 'rongrieu',
    tintucspc : 'tintucspc',
    hoatdongtapthe: 'hoatdongtapthe',
    hoichosukien : 'hoichosukien',
    bieuduongkhenthuong : 'bieuduongkhenthuong',
    tintucnongnghiep : 'tintucnongnghiep',
    chinhsachphapluat : 'chinhsachphapluat',
    hdbsct: 'hdbsct',
    huongdankt : 'huongdankt',
    nongdanspc : 'nongdanspc',
    tailieukt: 'tailieukt',
    bsct2023 : 'bsct2023',
    bsct2021 : 'bsct2021',
    tintucsukien : 'tintucsukien',
    media: 'media',
    sliders : 'sliders',
    categoriesbsct : 'categoriesbsct',
    bsct: 'bsct'
}